Portfolio setup(Desktop version)
collinsmezie/collinsmezie.github.io pull request #10
Opened 2022-02-18 11:14 UTC by collinsmezie

Desktop version of project portfolio, with completed projects , project description, developer contact and form.

2022-02-18 11:59 UTC, Deepakdanger requested changes
Hi @collinsmezie, 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-18 11:59 UTC, Deepakdanger commented on index.html
>      <div class="form-section">
- [ ] In **Desktop version** ,The `Contact me` section should have same design as original website. Kindly fix the `top-left design` and background image of the `contact me` section. **Hint** You can do that by using `border radius` for design.
- Your website 
![gerge](https://user-images.githubusercontent.com/26767383/154677436-44cbd7ee-34ae-4413-85f8-9f5c192846d5.PNG)

- Original website
![gwg](https://user-images.githubusercontent.com/26767383/154677525-d9ef82c9-2331-44b9-92bf-7534c4585407.PNG)

2022-02-18 11:59 UTC, Deepakdanger commented on index.html
> +    <div class="About">
- [ ]  In **Desktop version**, The `About Myself` section should have the same design as the original website. Kindly fix the top-right design. Hint You can do that by using border-radius for design.
- Your website  
![gergsas](https://user-images.githubusercontent.com/26767383/154678015-1d32fc44-28c2-400f-b294-c6fbe020d1b2.PNG)

- Original website
![ngfbdf](https://user-images.githubusercontent.com/26767383/154678086-7b7002e1-de42-422e-bb5c-377446927031.PNG)

2022-02-18 11:59 UTC, Deepakdanger commented on index.html
>        <div class="intro">
- [ ] In **Desktop version**, The `top section` should have the same design as the original website. Kindly fix the bottom-left design. Hint You can do that by using `border-radius` for design.
- Your website 
![ssdg](https://user-images.githubusercontent.com/26767383/154678426-5d9e9a14-009b-44b1-ba0f-069fb0a98051.PNG)
- Original website 
![ffdvfv](https://user-images.githubusercontent.com/26767383/154678456-7feb0b94-38be-4261-b722-1d62a32c760d.PNG)

2022-02-18 11:59 UTC, Deepakdanger commented on index.html
>      <div id="projects-section">
- [ ] Change the `background color` of this section as in the original website, so the design will be easily seen.

2022-02-18 16:40 UTC, ReshyResh requested changes
# Hi @collinsmezie , 

### Great work on making the changes requested by a previous reviewer 👏 
#### You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-18 16:40 UTC, ReshyResh commented on styles.css
> +@media (min-width: 600px) {
- [ ] Please make sure the range of the desktop view is between `992px` and `1100px`, as per requirement.

2022-02-18 16:40 UTC, ReshyResh commented on styles.css
> +  }
- [ ] Giving the content fixed sizes makes it non responsive, and the content will go out of it's boundaries when resized, as in the picture below. Please solve this issue by making the content width dynamic and not fixed.

![](https://i.imgur.com/xrjgdEn.png)

2022-02-18 16:40 UTC, ReshyResh commented on styles.css
> +  }
- [ ] Please add some padding to these sections to better match the template.

![](https://i.imgur.com/DYuW5J4.png)

2022-02-18 16:40 UTC, ReshyResh commented on styles.css
> +  }
- [ ] Please make sure the mobile version doesn't change when coding the desktop one. Currently, the mobile version is stuck to the left side of the screen, kindly fix that.

![](https://i.imgur.com/Q7WTknb.png)

2022-02-19 08:11 UTC, RolandM99 approved these changes
<h1>Status: Approve 🥇 ✔</h1>
Hi @collinsmezie , 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
#### Congratulations on the hard work, now you can take a rest for the weekend! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

<img src="https://media.giphy.com/media/aNqEFrYVnsS52/giphy.gif" width="100%">

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-19 08:12 UTC, merged