Html form feature
collinsmezie/collinsmezie.github.io pull request #3
Opened 2022-02-15 16:31 UTC by collinsmezie

Html form interface, an essential program used in collecting client data and performing validations.

2022-02-15 17:01 UTC, AnselemOdims requested changes
### Hi @collinsmezie and @virag-ky, 
You guys have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Kindly make sure your PR has a descriptive title and summary
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!. You can use the tag @AnselemOdims for a quicker reply.

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-15 17:01 UTC, AnselemOdims commented on index.html
> +            placeholder="Write your message here"
- [ ] Good job on including the max length and placeholder but in order to activate the validation on submitting all inputs should have the `required` attribute. Please make sure all inputs have the required attribute.

2022-02-15 17:01 UTC, AnselemOdims commented on index.html
> +      </form>
- [ ] Even though you have put in a commendable effort in your design, the paragraph text is not properly aligned and the background image is not visible. Please make sure the text is aligned with the original design guidelines and the background shows up

### Your Design
![image](https://user-images.githubusercontent.com/43995830/154110788-48ab48fd-e588-4a3f-b3b8-d7a325d3c722.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/154110651-62f00b9d-bcae-4766-b5d3-36545f8800ef.png)

2022-02-16 06:22 UTC, ShoiraTa requested changes
Hi @collinsmezie ,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
Nice job working on required changes, your design looks awesome! ☀️ 

There is only one issue you forgot to address

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-16 06:22 UTC, ShoiraTa commented on index.html
> +          <input type="email" id="email" name="email" placeholder="Email" />
- [ ] As the previous reviewer mentioned, please make the email field required. Currently I can fill in the form without email and successfully submit

2022-02-16 07:58 UTC, BenMukebo approved these changes
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @collinsmezie** , 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight :1st_place_medal: 

- No Linter errors :heavy_check_mark: 
- Your Design looks awesome, keep rocking :rocket: 

## Optional suggestions

- [ OPTIONAL] Please, Write a meaningful title for your pull request and always add a short summary of changes introduced in the pull request. you can check the  [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-16 09:06 UTC, merged